version: '3.8'

services:
  spark-master:
    container_name: da-spark-master
    build: .
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    environment:
      - PYSPARK_PYTHON=/usr/local/bin/python3.10
      - PYSPARK_DRIVER_PYTHON=/usr/local/bin/python3.10
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'
    networks:
      - datenanalyse-spark

  spark-notebook:
    build: spark_notebook  # Build using the Dockerfile in the current directory
    container_name: jupyter-spark
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - PYSPARK_PYTHON=/usr/local/bin/python3.10
      - PYSPARK_DRIVER_PYTHON=/usr/local/bin/python3.10
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "8889:8888"
    depends_on:
      - spark-master
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - datenanalyse-spark

  spark-history-server:
    container_name: da-spark-history
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    environment:
      - PYSPARK_PYTHON=/usr/local/bin/python3.10
      - PYSPARK_DRIVER_PYTHON=/usr/local/bin/python3.10
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'
    networks:
      - datenanalyse-spark

  spark-worker:
    #    container_name: da-spark-worker
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    environment:
      - PYSPARK_PYTHON=/usr/local/bin/python3.10
      - PYSPARK_DRIVER_PYTHON=/usr/local/bin/python3.10
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    networks:
      - datenanalyse-spark

volumes:
  spark-logs:

networks:
  datenanalyse-spark:
    driver: bridge